name: Puppet show Notifier

on: [push]

jobs:
  test:
    name: Test ðŸš¦
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Use correct Node version
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Cache node_modules
        id: cache_node_modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.cache_node_modules.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: |
          npm ci
      - name: Start docker
        run: npm run docker
      - name: Run tests
        run: npm test
