name: Puppet show Notifier

on: [push]

jobs:
  test:
    name: Test ðŸš¦
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Use correct Node version
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: |
          npm ci
      - name: Start docker
        run: npm run docker
      - name: Create env file
        run: cp .env.example .env
      - name: Run tests
        run: npm test
